### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by damianlluch** [dovuofficial/hedera-hardhat-tooling#14]
Hi, interesting to find a Hedera project with Hardhat.
I have some openzeppelin proxies on my architecture, such as a beacon and a transparent proxy.
Can I use the hardhat plugin for OZ proxies? I was developing manually without proxies with scripts... but if it is possible to do it as you did, it would be spectacular.

**Comment by damianlluch** [comment]
> Hey @damianlluch,
> 
> I am not well versed in all of the proxy contracts that OZ provides, however, I haven't had an issue with utilising/importing any of these contracts from OZ for deployment.
> 
> Feel free to pull this down and give it a crack if you want to give it a go, new only thing I mention is that Hedera's SC capabilities are still relatively new compared to other ecosystems, and I if there was an issue at all please just let us know

Thanks for the reply, I just created a template from your project. It's not clear to me where the OpenZeppelin lib imports should go to do the migration.
Can you please clarify?

Thanks

**Comment by damianlluch** [comment]
> Hey @damianlluch,
> 
> I am not well versed in all of the proxy contracts that OZ provides, however, I haven't had an issue with utilising/importing any of these contracts from OZ for deployment.
> 
> Feel free to pull this down and give it a crack if you want to give it a go, new only thing I mention is that Hedera's SC capabilities are still relatively new compared to other ecosystems, and I if there was an issue at all please just let us know

Hi, I am getting this error when displaying contracts.
I have put my credentials in the .env for testnet, accountId and privateKey.

Any suggestions?

thanks

failed precheck with status PLATFORM_NOT_ACTIVE

**Comment by damianlluch** [comment]
@mattsmithies 

Could you give me an update on what I have asked you about?

On the other hand, in the Markefile, you have the contract displayed directly. For the case I asked you, I need to use the OpenZepplelin plugin for the use of proxies. Can you think of a way to add this?

thanks

```
# Deploy a smart contract to Hedera testnet
deploy:
	hardhat compile
	hardhat deploy --contract $(CONTRACT)

# Target a specific contract based on the "test/*-contract.js" format
test-contract:
	hardhat test test/$(shell echo $(CONTRACT) | tr A-Z a-z)-contract.js

# Deploy a contract and test in one step
deploy-test:
	make deploy CONTRACT=$(CONTRACT)
	make test-contract CONTRACT=$(CONTRACT)

## This is the solidity contract name (example of custom commands)
CONTRACT = "StakableProject"

## Simply a utility to get the contract into a state that is completely tested and employed given a custom environment/owner, with demo projects
deploy-test-stakable-base-contract:
	make deploy CONTRACT=$(CONTRACT)
	hardhat add-demo-projects
	make test-contract CONTRACT=$(CONTRACT)

# Deploy timelock example contract and run tests
deploy-test-timelock:
	make deploy-test CONTRACT=TimelockExample

```

**Comment by mattsmithies** [comment]
@damianlluch apologies for not getting back earlier.

1. Regards to imports you would import your dependencies for any contract. [See HelloWorld](https://github.com/dovuofficial/hedera-hardhat-tooling/blob/main/contracts/HelloWorld.sol)
2. In terms of an ongoing migration workflow you'll need to build your own using the Hardhats approach with [Task Runners](https://hardhat.org/hardhat-runner/docs/other-guides/truffle-migration)
3. The **PLATFORM_NOT_ACTIVE** is an error from testnet that indicates that one or more of the Hedera nodes is offline, you can view the [network status](https://status.hedera.com/) to double check. Furthermore, you can target the [specific nodes the client is talking](https://github.com/dovuofficial/hedera-hardhat-tooling/blob/main/support/network.js#L8) to with the [network documentation](https://docs.hedera.com/guides/docs/sdks/client#1.-configure-your-hedera-network).
4. Finally, the MakeFile provides the capability to add whatever commands to need to run your own workflows, to trigger specific scripts or particular [Hardhat tasks](https://hardhat.org/hardhat-runner/docs/advanced/create-task#creating-a-task).

In the case, above my aim was to provide a basic scaffold for others to add the particular contractor working for deployment, swap out the contract name or duplicate a command.

I should note that Hedera Contracts will be more EVM compatible moving forward with their [RPC-JSON relay HIP](https://hips.hedera.com/hip/hip-482) so it's likely that default usage of Truffle/Hardhat will work rather than this intermediary work.

Hope that helps you on your quest!

**Comment by mattsmithies** [comment]
Closing issue as stale
